import Foundation
import Testing
@testable import ScarfCore

/// P57b findings 1 and 2: `display.busy_ack_enabled`.
///
/// **There is no `.strip()` on this key's path.** P57 routed it through
/// `HermesYAML.strippedScalar` on the theory that every Hermes reader strips;
/// this one does not. The chain, re-opened at `v2026.9.7`:
///
///   - `gateway/run.py:1810-1813` — `_DISPLAY_ENV_BRIDGE` maps
///     `busy_ack_enabled` to `HERMES_GATEWAY_BUSY_ACK_ENABLED`;
///   - `gateway/run.py:1816-1821` — `_bridge_section_to_env` does
///     `os.environ[env_var] = str(section[cfg_key])`, **unstripped**;
///   - `gateway/run_busy.py:727` —
///     `if os.environ.get("HERMES_GATEWAY_BUSY_ACK_ENABLED", "true").lower()
///     != "true": … return True` — anything but the word `true` DISABLES.
///
/// So quoted `' true'` is the Python `str` `" true"`, whose `.lower()` is not
/// `"true"`, and the ack is OFF on the host — while post-P57 Scarf stripped
/// it and drew it ON. And quoted `'yes'` / `'on'` are the strings `yes`/`on`,
/// also OFF, which the `["true","yes","on"]` word list got wrong long before
/// P57: that list is right only for a BARE scalar, where PyYAML's bool
/// resolver has already turned all nine spellings into `True` → `str(True)`.
///
/// The corpus below is the whole argument. 51 spellings × the styles and
/// paddings each can legally carry on one line = **918 rows**, every
/// `busyAck` and `token` column printed by PyYAML 6.0.3 running
/// `yaml.safe_load("k: " + written)` and then Hermes's two comparisons
/// verbatim. Nothing here is reasoned about; it is transcribed.
@Suite("P57b — busy_ack_enabled has no strip, and quoted `yes` is a string")
struct HermesP57bBusyAckCorpusTests {

    /// `written` is the literal text after `k: `. `token` is `_bool_token`'s
    /// answer (`gateway/config.py:29-32`), `ack` is `run_busy.py:727`'s
    /// (true = ack ENABLED).
    struct R: Sendable {
        let written: String, token: Bool?, ack: Bool
        init(_ w: String, _ t: Bool?, _ a: Bool) { written = w; token = t; ack = a }
    }

    static let corpus: [R] = [
        R("true", true, true),
        R("'true'", true, true),
        R("\"true\"", true, true),
        R("' true'", true, false),
        R("\" true\"", true, false),
        R("'true '", true, false),
        R("\"true \"", true, false),
        R("' true '", true, false),
        R("\" true \"", true, false),
        R("'\ttrue'", true, false),
        R("\"\\ttrue\"", true, false),
        R("'true\t'", true, false),
        R("\"true\\t\"", true, false),
        R("\"true\\n\"", true, false),
        R("\"\\ntrue\"", true, false),
        R("'true\u{A0}'", true, false),
        R("\"true\\xa0\"", true, false),
        R("\"true\\r\\n\"", true, false),
        R("True", true, true),
        R("'True'", true, true),
        R("\"True\"", true, true),
        R("' True'", true, false),
        R("\" True\"", true, false),
        R("'True '", true, false),
        R("\"True \"", true, false),
        R("' True '", true, false),
        R("\" True \"", true, false),
        R("'\tTrue'", true, false),
        R("\"\\tTrue\"", true, false),
        R("'True\t'", true, false),
        R("\"True\\t\"", true, false),
        R("\"True\\n\"", true, false),
        R("\"\\nTrue\"", true, false),
        R("'True\u{A0}'", true, false),
        R("\"True\\xa0\"", true, false),
        R("\"True\\r\\n\"", true, false),
        R("TRUE", true, true),
        R("'TRUE'", true, true),
        R("\"TRUE\"", true, true),
        R("' TRUE'", true, false),
        R("\" TRUE\"", true, false),
        R("'TRUE '", true, false),
        R("\"TRUE \"", true, false),
        R("' TRUE '", true, false),
        R("\" TRUE \"", true, false),
        R("'\tTRUE'", true, false),
        R("\"\\tTRUE\"", true, false),
        R("'TRUE\t'", true, false),
        R("\"TRUE\\t\"", true, false),
        R("\"TRUE\\n\"", true, false),
        R("\"\\nTRUE\"", true, false),
        R("'TRUE\u{A0}'", true, false),
        R("\"TRUE\\xa0\"", true, false),
        R("\"TRUE\\r\\n\"", true, false),
        R("tRuE", true, true),
        R("'tRuE'", true, true),
        R("\"tRuE\"", true, true),
        R("' tRuE'", true, false),
        R("\" tRuE\"", true, false),
        R("'tRuE '", true, false),
        R("\"tRuE \"", true, false),
        R("' tRuE '", true, false),
        R("\" tRuE \"", true, false),
        R("'\ttRuE'", true, false),
        R("\"\\ttRuE\"", true, false),
        R("'tRuE\t'", true, false),
        R("\"tRuE\\t\"", true, false),
        R("\"tRuE\\n\"", true, false),
        R("\"\\ntRuE\"", true, false),
        R("'tRuE\u{A0}'", true, false),
        R("\"tRuE\\xa0\"", true, false),
        R("\"tRuE\\r\\n\"", true, false),
        R("false", false, false),
        R("'false'", false, false),
        R("\"false\"", false, false),
        R("' false'", false, false),
        R("\" false\"", false, false),
        R("'false '", false, false),
        R("\"false \"", false, false),
        R("' false '", false, false),
        R("\" false \"", false, false),
        R("'\tfalse'", false, false),
        R("\"\\tfalse\"", false, false),
        R("'false\t'", false, false),
        R("\"false\\t\"", false, false),
        R("\"false\\n\"", false, false),
        R("\"\\nfalse\"", false, false),
        R("'false\u{A0}'", false, false),
        R("\"false\\xa0\"", false, false),
        R("\"false\\r\\n\"", false, false),
        R("False", false, false),
        R("'False'", false, false),
        R("\"False\"", false, false),
        R("' False'", false, false),
        R("\" False\"", false, false),
        R("'False '", false, false),
        R("\"False \"", false, false),
        R("' False '", false, false),
        R("\" False \"", false, false),
        R("'\tFalse'", false, false),
        R("\"\\tFalse\"", false, false),
        R("'False\t'", false, false),
        R("\"False\\t\"", false, false),
        R("\"False\\n\"", false, false),
        R("\"\\nFalse\"", false, false),
        R("'False\u{A0}'", false, false),
        R("\"False\\xa0\"", false, false),
        R("\"False\\r\\n\"", false, false),
        R("FALSE", false, false),
        R("'FALSE'", false, false),
        R("\"FALSE\"", false, false),
        R("' FALSE'", false, false),
        R("\" FALSE\"", false, false),
        R("'FALSE '", false, false),
        R("\"FALSE \"", false, false),
        R("' FALSE '", false, false),
        R("\" FALSE \"", false, false),
        R("'\tFALSE'", false, false),
        R("\"\\tFALSE\"", false, false),
        R("'FALSE\t'", false, false),
        R("\"FALSE\\t\"", false, false),
        R("\"FALSE\\n\"", false, false),
        R("\"\\nFALSE\"", false, false),
        R("'FALSE\u{A0}'", false, false),
        R("\"FALSE\\xa0\"", false, false),
        R("\"FALSE\\r\\n\"", false, false),
        R("fAlSe", false, false),
        R("'fAlSe'", false, false),
        R("\"fAlSe\"", false, false),
        R("' fAlSe'", false, false),
        R("\" fAlSe\"", false, false),
        R("'fAlSe '", false, false),
        R("\"fAlSe \"", false, false),
        R("' fAlSe '", false, false),
        R("\" fAlSe \"", false, false),
        R("'\tfAlSe'", false, false),
        R("\"\\tfAlSe\"", false, false),
        R("'fAlSe\t'", false, false),
        R("\"fAlSe\\t\"", false, false),
        R("\"fAlSe\\n\"", false, false),
        R("\"\\nfAlSe\"", false, false),
        R("'fAlSe\u{A0}'", false, false),
        R("\"fAlSe\\xa0\"", false, false),
        R("\"fAlSe\\r\\n\"", false, false),
        R("yes", true, true),
        R("'yes'", true, false),
        R("\"yes\"", true, false),
        R("' yes'", true, false),
        R("\" yes\"", true, false),
        R("'yes '", true, false),
        R("\"yes \"", true, false),
        R("' yes '", true, false),
        R("\" yes \"", true, false),
        R("'\tyes'", true, false),
        R("\"\\tyes\"", true, false),
        R("'yes\t'", true, false),
        R("\"yes\\t\"", true, false),
        R("\"yes\\n\"", true, false),
        R("\"\\nyes\"", true, false),
        R("'yes\u{A0}'", true, false),
        R("\"yes\\xa0\"", true, false),
        R("\"yes\\r\\n\"", true, false),
        R("Yes", true, true),
        R("'Yes'", true, false),
        R("\"Yes\"", true, false),
        R("' Yes'", true, false),
        R("\" Yes\"", true, false),
        R("'Yes '", true, false),
        R("\"Yes \"", true, false),
        R("' Yes '", true, false),
        R("\" Yes \"", true, false),
        R("'\tYes'", true, false),
        R("\"\\tYes\"", true, false),
        R("'Yes\t'", true, false),
        R("\"Yes\\t\"", true, false),
        R("\"Yes\\n\"", true, false),
        R("\"\\nYes\"", true, false),
        R("'Yes\u{A0}'", true, false),
        R("\"Yes\\xa0\"", true, false),
        R("\"Yes\\r\\n\"", true, false),
        R("YES", true, true),
        R("'YES'", true, false),
        R("\"YES\"", true, false),
        R("' YES'", true, false),
        R("\" YES\"", true, false),
        R("'YES '", true, false),
        R("\"YES \"", true, false),
        R("' YES '", true, false),
        R("\" YES \"", true, false),
        R("'\tYES'", true, false),
        R("\"\\tYES\"", true, false),
        R("'YES\t'", true, false),
        R("\"YES\\t\"", true, false),
        R("\"YES\\n\"", true, false),
        R("\"\\nYES\"", true, false),
        R("'YES\u{A0}'", true, false),
        R("\"YES\\xa0\"", true, false),
        R("\"YES\\r\\n\"", true, false),
        R("no", false, false),
        R("'no'", false, false),
        R("\"no\"", false, false),
        R("' no'", false, false),
        R("\" no\"", false, false),
        R("'no '", false, false),
        R("\"no \"", false, false),
        R("' no '", false, false),
        R("\" no \"", false, false),
        R("'\tno'", false, false),
        R("\"\\tno\"", false, false),
        R("'no\t'", false, false),
        R("\"no\\t\"", false, false),
        R("\"no\\n\"", false, false),
        R("\"\\nno\"", false, false),
        R("'no\u{A0}'", false, false),
        R("\"no\\xa0\"", false, false),
        R("\"no\\r\\n\"", false, false),
        R("No", false, false),
        R("'No'", false, false),
        R("\"No\"", false, false),
        R("' No'", false, false),
        R("\" No\"", false, false),
        R("'No '", false, false),
        R("\"No \"", false, false),
        R("' No '", false, false),
        R("\" No \"", false, false),
        R("'\tNo'", false, false),
        R("\"\\tNo\"", false, false),
        R("'No\t'", false, false),
        R("\"No\\t\"", false, false),
        R("\"No\\n\"", false, false),
        R("\"\\nNo\"", false, false),
        R("'No\u{A0}'", false, false),
        R("\"No\\xa0\"", false, false),
        R("\"No\\r\\n\"", false, false),
        R("NO", false, false),
        R("'NO'", false, false),
        R("\"NO\"", false, false),
        R("' NO'", false, false),
        R("\" NO\"", false, false),
        R("'NO '", false, false),
        R("\"NO \"", false, false),
        R("' NO '", false, false),
        R("\" NO \"", false, false),
        R("'\tNO'", false, false),
        R("\"\\tNO\"", false, false),
        R("'NO\t'", false, false),
        R("\"NO\\t\"", false, false),
        R("\"NO\\n\"", false, false),
        R("\"\\nNO\"", false, false),
        R("'NO\u{A0}'", false, false),
        R("\"NO\\xa0\"", false, false),
        R("\"NO\\r\\n\"", false, false),
        R("on", true, true),
        R("'on'", true, false),
        R("\"on\"", true, false),
        R("' on'", true, false),
        R("\" on\"", true, false),
        R("'on '", true, false),
        R("\"on \"", true, false),
        R("' on '", true, false),
        R("\" on \"", true, false),
        R("'\ton'", true, false),
        R("\"\\ton\"", true, false),
        R("'on\t'", true, false),
        R("\"on\\t\"", true, false),
        R("\"on\\n\"", true, false),
        R("\"\\non\"", true, false),
        R("'on\u{A0}'", true, false),
        R("\"on\\xa0\"", true, false),
        R("\"on\\r\\n\"", true, false),
        R("On", true, true),
        R("'On'", true, false),
        R("\"On\"", true, false),
        R("' On'", true, false),
        R("\" On\"", true, false),
        R("'On '", true, false),
        R("\"On \"", true, false),
        R("' On '", true, false),
        R("\" On \"", true, false),
        R("'\tOn'", true, false),
        R("\"\\tOn\"", true, false),
        R("'On\t'", true, false),
        R("\"On\\t\"", true, false),
        R("\"On\\n\"", true, false),
        R("\"\\nOn\"", true, false),
        R("'On\u{A0}'", true, false),
        R("\"On\\xa0\"", true, false),
        R("\"On\\r\\n\"", true, false),
        R("ON", true, true),
        R("'ON'", true, false),
        R("\"ON\"", true, false),
        R("' ON'", true, false),
        R("\" ON\"", true, false),
        R("'ON '", true, false),
        R("\"ON \"", true, false),
        R("' ON '", true, false),
        R("\" ON \"", true, false),
        R("'\tON'", true, false),
        R("\"\\tON\"", true, false),
        R("'ON\t'", true, false),
        R("\"ON\\t\"", true, false),
        R("\"ON\\n\"", true, false),
        R("\"\\nON\"", true, false),
        R("'ON\u{A0}'", true, false),
        R("\"ON\\xa0\"", true, false),
        R("\"ON\\r\\n\"", true, false),
        R("off", false, false),
        R("'off'", false, false),
        R("\"off\"", false, false),
        R("' off'", false, false),
        R("\" off\"", false, false),
        R("'off '", false, false),
        R("\"off \"", false, false),
        R("' off '", false, false),
        R("\" off \"", false, false),
        R("'\toff'", false, false),
        R("\"\\toff\"", false, false),
        R("'off\t'", false, false),
        R("\"off\\t\"", false, false),
        R("\"off\\n\"", false, false),
        R("\"\\noff\"", false, false),
        R("'off\u{A0}'", false, false),
        R("\"off\\xa0\"", false, false),
        R("\"off\\r\\n\"", false, false),
        R("Off", false, false),
        R("'Off'", false, false),
        R("\"Off\"", false, false),
        R("' Off'", false, false),
        R("\" Off\"", false, false),
        R("'Off '", false, false),
        R("\"Off \"", false, false),
        R("' Off '", false, false),
        R("\" Off \"", false, false),
        R("'\tOff'", false, false),
        R("\"\\tOff\"", false, false),
        R("'Off\t'", false, false),
        R("\"Off\\t\"", false, false),
        R("\"Off\\n\"", false, false),
        R("\"\\nOff\"", false, false),
        R("'Off\u{A0}'", false, false),
        R("\"Off\\xa0\"", false, false),
        R("\"Off\\r\\n\"", false, false),
        R("OFF", false, false),
        R("'OFF'", false, false),
        R("\"OFF\"", false, false),
        R("' OFF'", false, false),
        R("\" OFF\"", false, false),
        R("'OFF '", false, false),
        R("\"OFF \"", false, false),
        R("' OFF '", false, false),
        R("\" OFF \"", false, false),
        R("'\tOFF'", false, false),
        R("\"\\tOFF\"", false, false),
        R("'OFF\t'", false, false),
        R("\"OFF\\t\"", false, false),
        R("\"OFF\\n\"", false, false),
        R("\"\\nOFF\"", false, false),
        R("'OFF\u{A0}'", false, false),
        R("\"OFF\\xa0\"", false, false),
        R("\"OFF\\r\\n\"", false, false),
        R("y", nil, false),
        R("'y'", nil, false),
        R("\"y\"", nil, false),
        R("' y'", nil, false),
        R("\" y\"", nil, false),
        R("'y '", nil, false),
        R("\"y \"", nil, false),
        R("' y '", nil, false),
        R("\" y \"", nil, false),
        R("'\ty'", nil, false),
        R("\"\\ty\"", nil, false),
        R("'y\t'", nil, false),
        R("\"y\\t\"", nil, false),
        R("\"y\\n\"", nil, false),
        R("\"\\ny\"", nil, false),
        R("'y\u{A0}'", nil, false),
        R("\"y\\xa0\"", nil, false),
        R("\"y\\r\\n\"", nil, false),
        R("Y", nil, false),
        R("'Y'", nil, false),
        R("\"Y\"", nil, false),
        R("' Y'", nil, false),
        R("\" Y\"", nil, false),
        R("'Y '", nil, false),
        R("\"Y \"", nil, false),
        R("' Y '", nil, false),
        R("\" Y \"", nil, false),
        R("'\tY'", nil, false),
        R("\"\\tY\"", nil, false),
        R("'Y\t'", nil, false),
        R("\"Y\\t\"", nil, false),
        R("\"Y\\n\"", nil, false),
        R("\"\\nY\"", nil, false),
        R("'Y\u{A0}'", nil, false),
        R("\"Y\\xa0\"", nil, false),
        R("\"Y\\r\\n\"", nil, false),
        R("n", nil, false),
        R("'n'", nil, false),
        R("\"n\"", nil, false),
        R("' n'", nil, false),
        R("\" n\"", nil, false),
        R("'n '", nil, false),
        R("\"n \"", nil, false),
        R("' n '", nil, false),
        R("\" n \"", nil, false),
        R("'\tn'", nil, false),
        R("\"\\tn\"", nil, false),
        R("'n\t'", nil, false),
        R("\"n\\t\"", nil, false),
        R("\"n\\n\"", nil, false),
        R("\"\\nn\"", nil, false),
        R("'n\u{A0}'", nil, false),
        R("\"n\\xa0\"", nil, false),
        R("\"n\\r\\n\"", nil, false),
        R("N", nil, false),
        R("'N'", nil, false),
        R("\"N\"", nil, false),
        R("' N'", nil, false),
        R("\" N\"", nil, false),
        R("'N '", nil, false),
        R("\"N \"", nil, false),
        R("' N '", nil, false),
        R("\" N \"", nil, false),
        R("'\tN'", nil, false),
        R("\"\\tN\"", nil, false),
        R("'N\t'", nil, false),
        R("\"N\\t\"", nil, false),
        R("\"N\\n\"", nil, false),
        R("\"\\nN\"", nil, false),
        R("'N\u{A0}'", nil, false),
        R("\"N\\xa0\"", nil, false),
        R("\"N\\r\\n\"", nil, false),
        R("1", true, false),
        R("'1'", true, false),
        R("\"1\"", true, false),
        R("' 1'", true, false),
        R("\" 1\"", true, false),
        R("'1 '", true, false),
        R("\"1 \"", true, false),
        R("' 1 '", true, false),
        R("\" 1 \"", true, false),
        R("'\t1'", true, false),
        R("\"\\t1\"", true, false),
        R("'1\t'", true, false),
        R("\"1\\t\"", true, false),
        R("\"1\\n\"", true, false),
        R("\"\\n1\"", true, false),
        R("'1\u{A0}'", true, false),
        R("\"1\\xa0\"", true, false),
        R("\"1\\r\\n\"", true, false),
        R("0", false, false),
        R("'0'", false, false),
        R("\"0\"", false, false),
        R("' 0'", false, false),
        R("\" 0\"", false, false),
        R("'0 '", false, false),
        R("\"0 \"", false, false),
        R("' 0 '", false, false),
        R("\" 0 \"", false, false),
        R("'\t0'", false, false),
        R("\"\\t0\"", false, false),
        R("'0\t'", false, false),
        R("\"0\\t\"", false, false),
        R("\"0\\n\"", false, false),
        R("\"\\n0\"", false, false),
        R("'0\u{A0}'", false, false),
        R("\"0\\xa0\"", false, false),
        R("\"0\\r\\n\"", false, false),
        R("01", true, false),
        R("'01'", nil, false),
        R("\"01\"", nil, false),
        R("' 01'", nil, false),
        R("\" 01\"", nil, false),
        R("'01 '", nil, false),
        R("\"01 \"", nil, false),
        R("' 01 '", nil, false),
        R("\" 01 \"", nil, false),
        R("'\t01'", nil, false),
        R("\"\\t01\"", nil, false),
        R("'01\t'", nil, false),
        R("\"01\\t\"", nil, false),
        R("\"01\\n\"", nil, false),
        R("\"\\n01\"", nil, false),
        R("'01\u{A0}'", nil, false),
        R("\"01\\xa0\"", nil, false),
        R("\"01\\r\\n\"", nil, false),
        R("00", false, false),
        R("'00'", nil, false),
        R("\"00\"", nil, false),
        R("' 00'", nil, false),
        R("\" 00\"", nil, false),
        R("'00 '", nil, false),
        R("\"00 \"", nil, false),
        R("' 00 '", nil, false),
        R("\" 00 \"", nil, false),
        R("'\t00'", nil, false),
        R("\"\\t00\"", nil, false),
        R("'00\t'", nil, false),
        R("\"00\\t\"", nil, false),
        R("\"00\\n\"", nil, false),
        R("\"\\n00\"", nil, false),
        R("'00\u{A0}'", nil, false),
        R("\"00\\xa0\"", nil, false),
        R("\"00\\r\\n\"", nil, false),
        R("+1", true, false),
        R("'+1'", nil, false),
        R("\"+1\"", nil, false),
        R("' +1'", nil, false),
        R("\" +1\"", nil, false),
        R("'+1 '", nil, false),
        R("\"+1 \"", nil, false),
        R("' +1 '", nil, false),
        R("\" +1 \"", nil, false),
        R("'\t+1'", nil, false),
        R("\"\\t+1\"", nil, false),
        R("'+1\t'", nil, false),
        R("\"+1\\t\"", nil, false),
        R("\"+1\\n\"", nil, false),
        R("\"\\n+1\"", nil, false),
        R("'+1\u{A0}'", nil, false),
        R("\"+1\\xa0\"", nil, false),
        R("\"+1\\r\\n\"", nil, false),
        R("-1", nil, false),
        R("'-1'", nil, false),
        R("\"-1\"", nil, false),
        R("' -1'", nil, false),
        R("\" -1\"", nil, false),
        R("'-1 '", nil, false),
        R("\"-1 \"", nil, false),
        R("' -1 '", nil, false),
        R("\" -1 \"", nil, false),
        R("'\t-1'", nil, false),
        R("\"\\t-1\"", nil, false),
        R("'-1\t'", nil, false),
        R("\"-1\\t\"", nil, false),
        R("\"-1\\n\"", nil, false),
        R("\"\\n-1\"", nil, false),
        R("'-1\u{A0}'", nil, false),
        R("\"-1\\xa0\"", nil, false),
        R("\"-1\\r\\n\"", nil, false),
        R("-0", false, false),
        R("'-0'", nil, false),
        R("\"-0\"", nil, false),
        R("' -0'", nil, false),
        R("\" -0\"", nil, false),
        R("'-0 '", nil, false),
        R("\"-0 \"", nil, false),
        R("' -0 '", nil, false),
        R("\" -0 \"", nil, false),
        R("'\t-0'", nil, false),
        R("\"\\t-0\"", nil, false),
        R("'-0\t'", nil, false),
        R("\"-0\\t\"", nil, false),
        R("\"-0\\n\"", nil, false),
        R("\"\\n-0\"", nil, false),
        R("'-0\u{A0}'", nil, false),
        R("\"-0\\xa0\"", nil, false),
        R("\"-0\\r\\n\"", nil, false),
        R("0x1", true, false),
        R("'0x1'", nil, false),
        R("\"0x1\"", nil, false),
        R("' 0x1'", nil, false),
        R("\" 0x1\"", nil, false),
        R("'0x1 '", nil, false),
        R("\"0x1 \"", nil, false),
        R("' 0x1 '", nil, false),
        R("\" 0x1 \"", nil, false),
        R("'\t0x1'", nil, false),
        R("\"\\t0x1\"", nil, false),
        R("'0x1\t'", nil, false),
        R("\"0x1\\t\"", nil, false),
        R("\"0x1\\n\"", nil, false),
        R("\"\\n0x1\"", nil, false),
        R("'0x1\u{A0}'", nil, false),
        R("\"0x1\\xa0\"", nil, false),
        R("\"0x1\\r\\n\"", nil, false),
        R("0x0", false, false),
        R("'0x0'", nil, false),
        R("\"0x0\"", nil, false),
        R("' 0x0'", nil, false),
        R("\" 0x0\"", nil, false),
        R("'0x0 '", nil, false),
        R("\"0x0 \"", nil, false),
        R("' 0x0 '", nil, false),
        R("\" 0x0 \"", nil, false),
        R("'\t0x0'", nil, false),
        R("\"\\t0x0\"", nil, false),
        R("'0x0\t'", nil, false),
        R("\"0x0\\t\"", nil, false),
        R("\"0x0\\n\"", nil, false),
        R("\"\\n0x0\"", nil, false),
        R("'0x0\u{A0}'", nil, false),
        R("\"0x0\\xa0\"", nil, false),
        R("\"0x0\\r\\n\"", nil, false),
        R("0b1", true, false),
        R("'0b1'", nil, false),
        R("\"0b1\"", nil, false),
        R("' 0b1'", nil, false),
        R("\" 0b1\"", nil, false),
        R("'0b1 '", nil, false),
        R("\"0b1 \"", nil, false),
        R("' 0b1 '", nil, false),
        R("\" 0b1 \"", nil, false),
        R("'\t0b1'", nil, false),
        R("\"\\t0b1\"", nil, false),
        R("'0b1\t'", nil, false),
        R("\"0b1\\t\"", nil, false),
        R("\"0b1\\n\"", nil, false),
        R("\"\\n0b1\"", nil, false),
        R("'0b1\u{A0}'", nil, false),
        R("\"0b1\\xa0\"", nil, false),
        R("\"0b1\\r\\n\"", nil, false),
        R("0b0", false, false),
        R("'0b0'", nil, false),
        R("\"0b0\"", nil, false),
        R("' 0b0'", nil, false),
        R("\" 0b0\"", nil, false),
        R("'0b0 '", nil, false),
        R("\"0b0 \"", nil, false),
        R("' 0b0 '", nil, false),
        R("\" 0b0 \"", nil, false),
        R("'\t0b0'", nil, false),
        R("\"\\t0b0\"", nil, false),
        R("'0b0\t'", nil, false),
        R("\"0b0\\t\"", nil, false),
        R("\"0b0\\n\"", nil, false),
        R("\"\\n0b0\"", nil, false),
        R("'0b0\u{A0}'", nil, false),
        R("\"0b0\\xa0\"", nil, false),
        R("\"0b0\\r\\n\"", nil, false),
        R("1_0", nil, false),
        R("'1_0'", nil, false),
        R("\"1_0\"", nil, false),
        R("' 1_0'", nil, false),
        R("\" 1_0\"", nil, false),
        R("'1_0 '", nil, false),
        R("\"1_0 \"", nil, false),
        R("' 1_0 '", nil, false),
        R("\" 1_0 \"", nil, false),
        R("'\t1_0'", nil, false),
        R("\"\\t1_0\"", nil, false),
        R("'1_0\t'", nil, false),
        R("\"1_0\\t\"", nil, false),
        R("\"1_0\\n\"", nil, false),
        R("\"\\n1_0\"", nil, false),
        R("'1_0\u{A0}'", nil, false),
        R("\"1_0\\xa0\"", nil, false),
        R("\"1_0\\r\\n\"", nil, false),
        R("2", nil, false),
        R("'2'", nil, false),
        R("\"2\"", nil, false),
        R("' 2'", nil, false),
        R("\" 2\"", nil, false),
        R("'2 '", nil, false),
        R("\"2 \"", nil, false),
        R("' 2 '", nil, false),
        R("\" 2 \"", nil, false),
        R("'\t2'", nil, false),
        R("\"\\t2\"", nil, false),
        R("'2\t'", nil, false),
        R("\"2\\t\"", nil, false),
        R("\"2\\n\"", nil, false),
        R("\"\\n2\"", nil, false),
        R("'2\u{A0}'", nil, false),
        R("\"2\\xa0\"", nil, false),
        R("\"2\\r\\n\"", nil, false),
        R("truex", nil, false),
        R("'truex'", nil, false),
        R("\"truex\"", nil, false),
        R("' truex'", nil, false),
        R("\" truex\"", nil, false),
        R("'truex '", nil, false),
        R("\"truex \"", nil, false),
        R("' truex '", nil, false),
        R("\" truex \"", nil, false),
        R("'\ttruex'", nil, false),
        R("\"\\ttruex\"", nil, false),
        R("'truex\t'", nil, false),
        R("\"truex\\t\"", nil, false),
        R("\"truex\\n\"", nil, false),
        R("\"\\ntruex\"", nil, false),
        R("'truex\u{A0}'", nil, false),
        R("\"truex\\xa0\"", nil, false),
        R("\"truex\\r\\n\"", nil, false),
        R("null", nil, false),
        R("'null'", nil, false),
        R("\"null\"", nil, false),
        R("' null'", nil, false),
        R("\" null\"", nil, false),
        R("'null '", nil, false),
        R("\"null \"", nil, false),
        R("' null '", nil, false),
        R("\" null \"", nil, false),
        R("'\tnull'", nil, false),
        R("\"\\tnull\"", nil, false),
        R("'null\t'", nil, false),
        R("\"null\\t\"", nil, false),
        R("\"null\\n\"", nil, false),
        R("\"\\nnull\"", nil, false),
        R("'null\u{A0}'", nil, false),
        R("\"null\\xa0\"", nil, false),
        R("\"null\\r\\n\"", nil, false),
        R("~", nil, false),
        R("'~'", nil, false),
        R("\"~\"", nil, false),
        R("' ~'", nil, false),
        R("\" ~\"", nil, false),
        R("'~ '", nil, false),
        R("\"~ \"", nil, false),
        R("' ~ '", nil, false),
        R("\" ~ \"", nil, false),
        R("'\t~'", nil, false),
        R("\"\\t~\"", nil, false),
        R("'~\t'", nil, false),
        R("\"~\\t\"", nil, false),
        R("\"~\\n\"", nil, false),
        R("\"\\n~\"", nil, false),
        R("'~\u{A0}'", nil, false),
        R("\"~\\xa0\"", nil, false),
        R("\"~\\r\\n\"", nil, false),
        R("Null", nil, false),
        R("'Null'", nil, false),
        R("\"Null\"", nil, false),
        R("' Null'", nil, false),
        R("\" Null\"", nil, false),
        R("'Null '", nil, false),
        R("\"Null \"", nil, false),
        R("' Null '", nil, false),
        R("\" Null \"", nil, false),
        R("'\tNull'", nil, false),
        R("\"\\tNull\"", nil, false),
        R("'Null\t'", nil, false),
        R("\"Null\\t\"", nil, false),
        R("\"Null\\n\"", nil, false),
        R("\"\\nNull\"", nil, false),
        R("'Null\u{A0}'", nil, false),
        R("\"Null\\xa0\"", nil, false),
        R("\"Null\\r\\n\"", nil, false),
        R("1:30", nil, false),
        R("'1:30'", nil, false),
        R("\"1:30\"", nil, false),
        R("' 1:30'", nil, false),
        R("\" 1:30\"", nil, false),
        R("'1:30 '", nil, false),
        R("\"1:30 \"", nil, false),
        R("' 1:30 '", nil, false),
        R("\" 1:30 \"", nil, false),
        R("'\t1:30'", nil, false),
        R("\"\\t1:30\"", nil, false),
        R("'1:30\t'", nil, false),
        R("\"1:30\\t\"", nil, false),
        R("\"1:30\\n\"", nil, false),
        R("\"\\n1:30\"", nil, false),
        R("'1:30\u{A0}'", nil, false),
        R("\"1:30\\xa0\"", nil, false),
        R("\"1:30\\r\\n\"", nil, false),
        R("0o1", nil, false),
        R("'0o1'", nil, false),
        R("\"0o1\"", nil, false),
        R("' 0o1'", nil, false),
        R("\" 0o1\"", nil, false),
        R("'0o1 '", nil, false),
        R("\"0o1 \"", nil, false),
        R("' 0o1 '", nil, false),
        R("\" 0o1 \"", nil, false),
        R("'\t0o1'", nil, false),
        R("\"\\t0o1\"", nil, false),
        R("'0o1\t'", nil, false),
        R("\"0o1\\t\"", nil, false),
        R("\"0o1\\n\"", nil, false),
        R("\"\\n0o1\"", nil, false),
        R("'0o1\u{A0}'", nil, false),
        R("\"0o1\\xa0\"", nil, false),
        R("\"0o1\\r\\n\"", nil, false),
        R("1.0", nil, false),
        R("'1.0'", nil, false),
        R("\"1.0\"", nil, false),
        R("' 1.0'", nil, false),
        R("\" 1.0\"", nil, false),
        R("'1.0 '", nil, false),
        R("\"1.0 \"", nil, false),
        R("' 1.0 '", nil, false),
        R("\" 1.0 \"", nil, false),
        R("'\t1.0'", nil, false),
        R("\"\\t1.0\"", nil, false),
        R("'1.0\t'", nil, false),
        R("\"1.0\\t\"", nil, false),
        R("\"1.0\\n\"", nil, false),
        R("\"\\n1.0\"", nil, false),
        R("'1.0\u{A0}'", nil, false),
        R("\"1.0\\xa0\"", nil, false),
        R("\"1.0\\r\\n\"", nil, false),
        R("tru", nil, false),
        R("'tru'", nil, false),
        R("\"tru\"", nil, false),
        R("' tru'", nil, false),
        R("\" tru\"", nil, false),
        R("'tru '", nil, false),
        R("\"tru \"", nil, false),
        R("' tru '", nil, false),
        R("\" tru \"", nil, false),
        R("'\ttru'", nil, false),
        R("\"\\ttru\"", nil, false),
        R("'tru\t'", nil, false),
        R("\"tru\\t\"", nil, false),
        R("\"tru\\n\"", nil, false),
        R("\"\\ntru\"", nil, false),
        R("'tru\u{A0}'", nil, false),
        R("\"tru\\xa0\"", nil, false),
        R("\"tru\\r\\n\"", nil, false),
        R("tRue", true, true),
        R("'tRue'", true, true),
        R("\"tRue\"", true, true),
        R("' tRue'", true, false),
        R("\" tRue\"", true, false),
        R("'tRue '", true, false),
        R("\"tRue \"", true, false),
        R("' tRue '", true, false),
        R("\" tRue \"", true, false),
        R("'\ttRue'", true, false),
        R("\"\\ttRue\"", true, false),
        R("'tRue\t'", true, false),
        R("\"tRue\\t\"", true, false),
        R("\"tRue\\n\"", true, false),
        R("\"\\ntRue\"", true, false),
        R("'tRue\u{A0}'", true, false),
        R("\"tRue\\xa0\"", true, false),
        R("\"tRue\\r\\n\"", true, false),
        R("TruE", true, true),
        R("'TruE'", true, true),
        R("\"TruE\"", true, true),
        R("' TruE'", true, false),
        R("\" TruE\"", true, false),
        R("'TruE '", true, false),
        R("\"TruE \"", true, false),
        R("' TruE '", true, false),
        R("\" TruE \"", true, false),
        R("'\tTruE'", true, false),
        R("\"\\tTruE\"", true, false),
        R("'TruE\t'", true, false),
        R("\"TruE\\t\"", true, false),
        R("\"TruE\\n\"", true, false),
        R("\"\\nTruE\"", true, false),
        R("'TruE\u{A0}'", true, false),
        R("\"TruE\\xa0\"", true, false),
        R("\"TruE\\r\\n\"", true, false),
        R("oN", true, false),
        R("'oN'", true, false),
        R("\"oN\"", true, false),
        R("' oN'", true, false),
        R("\" oN\"", true, false),
        R("'oN '", true, false),
        R("\"oN \"", true, false),
        R("' oN '", true, false),
        R("\" oN \"", true, false),
        R("'\toN'", true, false),
        R("\"\\toN\"", true, false),
        R("'oN\t'", true, false),
        R("\"oN\\t\"", true, false),
        R("\"oN\\n\"", true, false),
        R("\"\\noN\"", true, false),
        R("'oN\u{A0}'", true, false),
        R("\"oN\\xa0\"", true, false),
        R("\"oN\\r\\n\"", true, false),
        R("yEs", true, false),
        R("'yEs'", true, false),
        R("\"yEs\"", true, false),
        R("' yEs'", true, false),
        R("\" yEs\"", true, false),
        R("'yEs '", true, false),
        R("\"yEs \"", true, false),
        R("' yEs '", true, false),
        R("\" yEs \"", true, false),
        R("'\tyEs'", true, false),
        R("\"\\tyEs\"", true, false),
        R("'yEs\t'", true, false),
        R("\"yEs\\t\"", true, false),
        R("\"yEs\\n\"", true, false),
        R("\"\\nyEs\"", true, false),
        R("'yEs\u{A0}'", true, false),
        R("\"yEs\\xa0\"", true, false),
        R("\"yEs\\r\\n\"", true, false),
        R("nO", false, false),
        R("'nO'", false, false),
        R("\"nO\"", false, false),
        R("' nO'", false, false),
        R("\" nO\"", false, false),
        R("'nO '", false, false),
        R("\"nO \"", false, false),
        R("' nO '", false, false),
        R("\" nO \"", false, false),
        R("'\tnO'", false, false),
        R("\"\\tnO\"", false, false),
        R("'nO\t'", false, false),
        R("\"nO\\t\"", false, false),
        R("\"nO\\n\"", false, false),
        R("\"\\nnO\"", false, false),
        R("'nO\u{A0}'", false, false),
        R("\"nO\\xa0\"", false, false),
        R("\"nO\\r\\n\"", false, false),
        R("oFf", false, false),
        R("'oFf'", false, false),
        R("\"oFf\"", false, false),
        R("' oFf'", false, false),
        R("\" oFf\"", false, false),
        R("'oFf '", false, false),
        R("\"oFf \"", false, false),
        R("' oFf '", false, false),
        R("\" oFf \"", false, false),
        R("'\toFf'", false, false),
        R("\"\\toFf\"", false, false),
        R("'oFf\t'", false, false),
        R("\"oFf\\t\"", false, false),
        R("\"oFf\\n\"", false, false),
        R("\"\\noFf\"", false, false),
        R("'oFf\u{A0}'", false, false),
        R("\"oFf\\xa0\"", false, false),
        R("\"oFf\\r\\n\"", false, false),
    ]

    /// The corpus is a measurement, and a measurement names its size. A
    /// silently shrunken table would turn "0 disagreements" into a claim
    /// about nothing.
    @Test func theCorpusIsTheSizeThisSuiteClaims() {
        #expect(Self.corpus.count == 918)
        #expect(Set(Self.corpus.map(\.written)).count == 918, "no duplicate rows")
        // The rows that MATTER: pre-fix Scarf answered ON for these.
        let enabled = Self.corpus.filter(\.ack)
        #expect(enabled.count == 24)
    }

    /// 0 disagreements over the 918 rows above — that is the claim, and this
    /// is where it is re-measured.
    @Test func busyAckMatchesTheOracleOverTheWholeCorpus() {
        var wrong: [String] = []
        for row in Self.corpus {
            let got = HermesConfig(yaml: "display:\n  busy_ack_enabled: \(row.written)\n")
                .displayBusyAckEnabled
            if got != row.ack { wrong.append("\(row.written) → \(got), PyYAML says \(row.ack)") }
        }
        #expect(wrong.isEmpty, "busy_ack disagreements: \(wrong.count)/\(Self.corpus.count) — \(wrong.prefix(20).joined(separator: "; "))")
    }

    /// The same corpus through `boolishValue`, whose vocabulary IS the
    /// universal boolish set — the other half of the P57b diff, and the
    /// reason the two readers must not share a normaliser.
    @Test func boolishValueMatchesTheOracleOverTheWholeCorpus() {
        var wrong: [String] = []
        for row in Self.corpus {
            let got = HermesYAML.boolishValue(row.written)
            if got != row.token { wrong.append("\(row.written) → \(String(describing: got)), PyYAML says \(String(describing: row.token))") }
        }
        #expect(wrong.isEmpty, "boolish disagreements: \(wrong.count)/\(Self.corpus.count) — \(wrong.prefix(20).joined(separator: "; "))")
    }

    /// The named regressions, spelled out so a failure reads as the finding
    /// rather than as a corpus row number.
    @Test func theNamedRegressions() {
        func ack(_ written: String) -> Bool {
            HermesConfig(yaml: "display:\n  busy_ack_enabled: \(written)\n").displayBusyAckEnabled
        }
        // Finding 1 — the strip P57 invented. Both pads DISABLE.
        #expect(ack("' true'") == false)
        #expect(ack("'true '") == false)
        #expect(ack("\" true\"") == false)
        #expect(ack("\"true\\t\"") == false)
        // …while the unpadded quoted word still enables.
        #expect(ack("'true'") == true)
        #expect(ack("\"TRUE\"") == true)
        // Finding 2 — quoted `yes`/`on` are strings, not bools.
        #expect(ack("'yes'") == false)
        #expect(ack("'on'") == false)
        #expect(ack("\"On\"") == false)
        // …and bare they are `True` → `str(True)` → enabled.
        #expect(ack("yes") == true)
        #expect(ack("on") == true)
        #expect(ack("YES") == true)
        // A bare spelling the resolver does NOT match is compared as its own
        // lowered text, so `tRuE` enables and `oN` does not.
        #expect(ack("tRuE") == true)
        #expect(ack("oN") == false)
        // Finding 2's pinned int: `str(1)` is `"1"`, never `"true"`.
        #expect(ack("1") == false)
        #expect(ack("01") == false)
        #expect(ack("0") == false)
        // Absent key → the bridge never runs → the "true" default.
        #expect(HermesConfig(yaml: "display:\n  busy_text_mode: full\n").displayBusyAckEnabled)
    }
}
