#!/usr/bin/env python3
"""
Validate scarf/scarf/Localizable.xcstrings.

Checks, in order:

1. The file is valid JSON in the String Catalog schema — `sourceLanguage`,
   and every localization shaped as
   `strings.<key>.localizations.<lang>.stringUnit.{state,value}` — and that
   it round-trips through json without loss.
2. Every translation's format specifiers match its source's (positional
   prefixes normalized, so `%1$@` counts as `%@`). Specifier drift is a
   runtime crash, not a cosmetic bug.
3. Every locale unit is `state: "translated"` and non-empty.
4. Coverage: every key that is real UI prose carries all six locales.
   Three kinds of hole are allowed and only three — the English stem+suffix
   plural hack, strings with no translatable words (pure specifiers and
   punctuation), and keys the catalog deliberately leaves in English
   (proper nouns, CLI/config literals, sample values, URL placeholders).

`--list-fallbacks` prints the third category, which is the list mirrored in
`scarf/scarfTests/LocalizationCatalogTests.swift` as `englishFallbackKeys`.

Usage:
    python3 tools/validate-catalog.py [--list-fallbacks]

Exits non-zero on any schema, parity or state error. Coverage gaps are
reported and also fail, since a new untranslated key is the thing this is
here to catch.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "scarf" / "scarf" / "Localizable.xcstrings"

LOCALES = {"de", "es", "fr", "ja", "pt-BR", "zh-Hans"}
SOURCE_LOCALE = "en"

SPECIFIER = re.compile(r"%(?:[0-9]+\$)?(@|lld|ld|d|f|lf)")

# Mirrors LocalizationCatalogTests.pluralHackExceptions.
PLURAL_HACK_EXCEPTIONS = {
    "%lld delivery failure%@",
    "Applied to %lld host%@",
}


def specifiers(text: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for kind in SPECIFIER.findall(text):
        counts[kind] = counts.get(kind, 0) + 1
    return counts


def is_plural_hack(key: str) -> bool:
    """English stem+suffix hack: a count plus a `%@` glued onto a word."""
    return "%lld" in key and re.search(r"[A-Za-z]%@", key) is not None


def has_no_translatable_words(key: str) -> bool:
    """Nothing but specifiers, digits and punctuation — nothing to translate."""
    return re.search(r"[A-Za-z]", SPECIFIER.sub("", key)) is None


def main() -> int:
    raw = CATALOG.read_text(encoding="utf-8")
    catalog = json.loads(raw)
    if json.loads(json.dumps(catalog)) != catalog:
        print("catalog does not round-trip through json")
        return 1

    errors: list[str] = []
    if catalog.get("sourceLanguage") != "en":
        errors.append(f"sourceLanguage is {catalog.get('sourceLanguage')!r}, expected 'en'")

    strings = catalog.get("strings")
    if not isinstance(strings, dict):
        print("catalog has no 'strings' object")
        return 1

    known_entry_fields = {"localizations", "comment", "isCommentAutoGenerated", "extractionState"}

    for key, entry in strings.items():
        for field in set(entry) - known_entry_fields:
            errors.append(f"unknown entry field {field!r} on {key!r}")

        for locale, localization in entry.get("localizations", {}).items():
            where = f"[{locale}] {key!r}"
            if locale != SOURCE_LOCALE and locale not in LOCALES:
                errors.append(f"unexpected locale column {where}")
            if set(localization) != {"stringUnit"}:
                errors.append(f"expected only 'stringUnit', got {sorted(localization)} {where}")
                continue
            unit = localization["stringUnit"]
            if not isinstance(unit, dict) or set(unit) != {"state", "value"}:
                errors.append(f"malformed stringUnit {where}")
                continue
            if locale == SOURCE_LOCALE:
                continue
            if unit["state"] != "translated":
                errors.append(f"state={unit['state']!r}, expected 'translated' {where}")
            if not unit["value"] and key:
                errors.append(f"empty translation {where}")
            if specifiers(unit["value"]) != specifiers(key):
                errors.append(f"specifier drift {where} -> {unit['value']!r}")

    # Coverage.
    fallbacks: list[str] = []
    hacks = 0
    format_only = 0
    for key, entry in strings.items():
        if is_plural_hack(key):
            hacks += 1
            if key not in PLURAL_HACK_EXCEPTIONS:
                translated = set(entry.get("localizations", {})) - {SOURCE_LOCALE}
                if translated:
                    errors.append(
                        f"plural-hack key must fall back to English: {key!r} "
                        f"→ {sorted(translated)}")
            continue
        if has_no_translatable_words(key):
            format_only += 1
            continue
        if LOCALES - set(entry.get("localizations", {})):
            fallbacks.append(key)

    if "--list-fallbacks" in sys.argv:
        for key in sorted(fallbacks):
            print(key)
        return 0

    for error in sorted(errors):
        print(f"error: {error}")

    print(f"keys: {len(strings)}")
    for locale in sorted(LOCALES):
        have = sum(1 for e in strings.values() if locale in e.get("localizations", {}))
        print(f"  {locale:8} {have}/{len(strings)} localized")
    print(f"plural-hack keys (English by design): {hacks}")
    print(f"no-translatable-words keys:           {format_only}")
    print(f"English-fallback keys:                {len(fallbacks)}")
    print(f"schema / parity / state errors:       {len(errors)}")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
